version: "3"
services:
  app-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DATABASE=esm-database
    ports:
      - "5433:5432"
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - app-db
    volumes:
      - ./jenkins_home/userContent/repository:/var/image_home
  jenkins:
    container_name: jenkins
    build: /docker/jenkins/.
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - ~/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock