version: "3"
services:
  app-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DATABASE=esm-database
    ports:
      - "5433:5432"
  app:
    build: /docker/application/.
    ports:
      - "8080:8080"
    depends_on:
      - app-db
  jenkins:
    build: jenkins:jenkins
    privileged: true
    user:
      root
    ports:
      - "8081:8080"
      - "50000:50000"
    container_name: app-jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - apt-get update
      - apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu (lsb_release -cs) stable"
      - apt-get update
      - apt-get install docker-ce docker-ce-cli containerd.io
  dind:
    image: docker:dind
    privileged: true
    container_name: dind
    ports:
      - "4444:4444"
    environment:
      PORT:
        4444
      DOCKER_DAEMON_ARGS:
        "-D"